repos:
        - repo: https://github.com/golangci/golangci-lint
          rev: v1.53.2
          hooks:
                  - id: golangci-lint
        - repo: https://github.com/dnephin/pre-commit-golang
          rev: v0.5.1
          hooks:
                  - id: go-lint
